import {
  View,
  Text,
  StyleSheet,
  TouchableOpacity,
  ScrollView,
} from "react-native";

import { useLocalSearchParams, useRouter } from "expo-router";

export default function ReportScreen() {
  const router = useRouter();

  const params = useLocalSearchParams();

  const {
    handwriting_score,
    speech_score,
    gait_score,
    final_score,
    risk_level,
    patient_name,
    patient_age,
    patient_gender,
  } = params;

  /**
   * Safe number conversion
   */
  const safeNumber = (value: any): number => {
    const num = Number(value);
    return isNaN(num) ? 0 : num;
  };

  /**
   * Safe text fallback
   */
  const safeText = (value: any): string => {
    if (value === undefined || value === null || value === "") return "N/A";
    return String(value);
  };

  /**
   * Risk color mapping
   */
  const getRiskColor = (level: any): string => {
    if (!level) return "#52c41a";

    const lower = String(level).toLowerCase();

    if (lower.includes("high")) return "#ff4d4f";
    if (lower.includes("moderate")) return "#faad14";
    return "#52c41a";
  };

  const today = new Date().toLocaleDateString();

  return (
    <ScrollView
      style={styles.container}
      contentContainerStyle={styles.scrollContent}
      showsVerticalScrollIndicator={false}
    >
      {/* Header */}
      <Text style={styles.header}>NeuroSeek Screening Report</Text>

      {/* Patient Info */}
      <View style={styles.section}>
        <Text style={styles.sectionTitle}>Patient Information</Text>

        <View style={styles.row}>
          <Text style={styles.label}>Name</Text>
          <Text style={styles.value}>{safeText(patient_name)}</Text>
        </View>

        <View style={styles.row}>
          <Text style={styles.label}>Age</Text>
          <Text style={styles.value}>{safeText(patient_age)}</Text>
        </View>

        <View style={styles.row}>
          <Text style={styles.label}>Gender</Text>
          <Text style={styles.value}>{safeText(patient_gender)}</Text>
        </View>

        <View style={styles.row}>
          <Text style={styles.label}>Date</Text>
          <Text style={styles.value}>{today}</Text>
        </View>
      </View>

      {/* Final Assessment */}
      <View style={styles.section}>
        <Text style={styles.sectionTitle}>Final Assessment</Text>

        <Text style={styles.finalScore}>
          {safeNumber(final_score).toFixed(2)}
        </Text>

        <Text
          style={[
            styles.riskLevel,
            { color: getRiskColor(risk_level) },
          ]}
        >
          {safeText(risk_level)}
        </Text>
      </View>

      {/* Detailed Scores */}
      <View style={styles.section}>
        <Text style={styles.sectionTitle}>Detailed Modality Scores</Text>

        <View style={styles.row}>
          <Text style={styles.label}>Handwriting Analysis</Text>
          <Text style={styles.value}>
            {safeNumber(handwriting_score).toFixed(2)}
          </Text>
        </View>

        <View style={styles.row}>
          <Text style={styles.label}>Speech Analysis</Text>
          <Text style={styles.value}>
            {safeNumber(speech_score).toFixed(2)}
          </Text>
        </View>

        <View style={styles.row}>
          <Text style={styles.label}>Gait Analysis</Text>
          <Text style={styles.value}>
            {safeNumber(gait_score).toFixed(2)}
          </Text>
        </View>
      </View>

      {/* Disclaimer */}
      <View style={styles.section}>
        <Text style={styles.sectionTitle}>Disclaimer</Text>

        <Text style={styles.disclaimer}>
          This report is generated by an AI-based screening system and is intended
          for preliminary assessment only. It does not constitute a medical
          diagnosis. Please consult a qualified healthcare professional for
          further evaluation and confirmation.
        </Text>
      </View>

      {/* Buttons */}
      <TouchableOpacity
        style={styles.primaryButton}
        onPress={() => router.replace("/dashboard")}
      >
        <Text style={styles.primaryText}>Back to Dashboard</Text>
      </TouchableOpacity>

      <TouchableOpacity
        style={styles.secondaryButton}
        onPress={() => router.replace("/patients")}
      >
        <Text style={styles.secondaryText}>Start New Screening</Text>
      </TouchableOpacity>
    </ScrollView>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#f5f7fb",
    padding: 16,
  },

  scrollContent: {
    paddingBottom: 40,
  },

  header: {
    fontSize: 22,
    fontWeight: "bold",
    marginBottom: 20,
  },

  section: {
    backgroundColor: "#fff",
    padding: 16,
    borderRadius: 12,
    marginBottom: 16,
    elevation: 2,
  },

  sectionTitle: {
    fontSize: 16,
    fontWeight: "600",
    marginBottom: 10,
  },

  row: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginVertical: 6,
  },

  label: {
    fontSize: 14,
    color: "#555",
  },

  value: {
    fontSize: 14,
    fontWeight: "500",
  },

  finalScore: {
    fontSize: 32,
    fontWeight: "bold",
    textAlign: "center",
    marginVertical: 10,
  },

  riskLevel: {
    fontSize: 18,
    fontWeight: "600",
    textAlign: "center",
  },

  disclaimer: {
    fontSize: 13,
    color: "#666",
    lineHeight: 18,
  },

  primaryButton: {
    backgroundColor: "#000",
    padding: 14,
    borderRadius: 10,
    alignItems: "center",
    marginBottom: 10,
  },

  primaryText: {
    color: "#fff",
    fontWeight: "600",
  },

  secondaryButton: {
    backgroundColor: "#eaeaea",
    padding: 14,
    borderRadius: 10,
    alignItems: "center",
  },

  secondaryText: {
    color: "#333",
    fontWeight: "600",
  },
});