"""add screening session tracking columns

Revision ID: b8229b1c494f
Revises: 74c0e638b39b
Create Date: 2026-02-20 17:08:51.929613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8229b1c494f'
down_revision: Union[str, Sequence[str], None] = '74c0e638b39b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('screenings', sa.Column('modalities_present', sa.String(), nullable=True))
    op.add_column('screenings', sa.Column('is_complete', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('screenings', 'is_complete')
    op.drop_column('screenings', 'modalities_present')
    # ### end Alembic commands ###
